# Generated by Django 3.2.3 on 2023-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCus', models.CharField(max_length=255)),
                ('passCus', models.CharField(max_length=255)),
                ('telCus', models.CharField(max_length=255)),
                ('buyUnit', models.IntegerField()),
                ('idLine', models.CharField(max_length=255)),
                ('namePage', models.CharField(max_length=255)),
                ('registWeb', models.CharField(max_length=255)),
                ('etc', models.TextField()),
            ],
        ),
    ]
