# Generated by Django 3.2.3 on 2023-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sex',
            field=models.CharField(blank=True, choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], max_length=10, verbose_name='เพศ'),
        ),
    ]
