# Generated by Django 3.2.3 on 2023-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0004_alter_sale_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
