# Generated by Django 3.2.3 on 2023-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0005_sale_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหุต'),
        ),
    ]
