# Generated by Django 3.2.3 on 2023-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0007_auto_20230530_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='call_back',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ช่องทางติดต่อกลับ'),
        ),
    ]
