# Generated by Django 3.2.3 on 2023-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0008_sale_call_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='unit',
            field=models.CharField(blank=True, choices=[('บาท', 'บาท'), ('ใบ', 'ใบ'), ('ยูสเซอร์', 'ยูสเซอร์')], max_length=10, null=True, verbose_name='หน่วย'),
        ),
    ]
