# Generated by Django 3.2.3 on 2023-05-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0025_auto_20230501_1642'),
        ('app_stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_dat',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='details',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pgive',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='presive',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='serial',
        ),
        migrations.AddField(
            model_name='stock',
            name='qutity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.profileuser'),
        ),
    ]
