# Generated by Django 3.2.3 on 2023-05-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0006_auto_20230502_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
