# Generated by Django 3.2.3 on 2023-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0007_auto_20230502_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
