# Generated by Django 3.2.3 on 2023-05-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0008_alter_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ชื่อไอเท็ม')),
                ('serial', models.CharField(max_length=60)),
                ('qutity', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qutity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stock.item'),
        ),
    ]
