# Generated by Django 3.2.3 on 2023-05-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0013_auto_20230502_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Create Category'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Create Item'},
        ),
    ]
