# Generated by Django 3.2.3 on 2023-05-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0014_auto_20230502_1630'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
