# Generated by Django 3.2.3 on 2023-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0015_alter_item_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quatity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
