# Generated by Django 3.2.3 on 2023-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0016_alter_stock_quatity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=60, verbose_name='ชื่อสินค้า'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qutity',
            field=models.PositiveIntegerField(null=True, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial',
            field=models.CharField(max_length=60, verbose_name='ซีเรียล'),
        ),
    ]
