# Generated by Django 3.2.3 on 2023-05-09 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_stock', '0018_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qutity',
        ),
        migrations.AddField(
            model_name='item',
            name='mouse',
            field=models.BooleanField(default=True, verbose_name='เม้าส์'),
        ),
        migrations.AddField(
            model_name='item',
            name='mouse_mat',
            field=models.BooleanField(default=True, verbose_name='เม้าส์'),
        ),
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
