# Generated by Django 3.2.3 on 2023-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0019_auto_20230509_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_mouse',
            field=models.CharField(max_length=60, null=True, verbose_name='ยี่ห้อเม้าส์'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mouse_mat',
            field=models.BooleanField(default=True, verbose_name='แผ่นรองเม้า'),
        ),
    ]
