# Generated by Django 3.2.3 on 2023-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0020_auto_20230509_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_mouse_mat',
            field=models.CharField(max_length=60, null=True, verbose_name='ชื่อแผ่นรองเม้าส์'),
        ),
    ]
