# Generated by Django 3.2.3 on 2023-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0021_auto_20230509_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='password_login',
            field=models.CharField(max_length=60, null=True, verbose_name='รหัสผ่าน'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial2',
            field=models.CharField(max_length=60, null=True, verbose_name='เลขที่เครื่อง'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_login',
            field=models.CharField(max_length=60, null=True, verbose_name='ชื่อผู้ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial',
            field=models.CharField(max_length=60, null=True, verbose_name='ซีเรียล'),
        ),
    ]
