# Generated by Django 3.2.3 on 2023-05-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0023_auto_20230509_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cable',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Cable'},
        ),
        migrations.AddField(
            model_name='cable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stock.category'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='detail',
            field=models.TextField(max_length=255, null=True, verbose_name='รายละเอียดเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='item_name',
            field=models.CharField(max_length=60, null=True, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='quatity',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวน'),
        ),
    ]
