# Generated by Django 3.2.3 on 2023-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0024_auto_20230509_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='item_name',
            field=models.CharField(max_length=60, null=True, verbose_name='ชนิดของสาย'),
        ),
    ]
