# Generated by Django 3.2.3 on 2023-05-09 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_stock', '0025_alter_cable_item_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Notebook',
        ),
    ]
