# Generated by Django 3.2.3 on 2023-05-09 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_stock', '0026_rename_item_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=60, null=True, verbose_name='ชื่อสินค้า')),
                ('quatity', models.PositiveIntegerField(default=0, verbose_name='จำนวน')),
                ('detail', models.TextField(max_length=255, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('date', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_stock.category')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Office',
            },
        ),
    ]
