# Generated by Django 3.2.3 on 2023-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0027_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='image_notebook'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='quatity',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวน'),
        ),
    ]
