# Generated by Django 3.2.3 on 2023-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0028_auto_20230509_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Create Notebook'},
        ),
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='image_notebook', verbose_name='อัพโหลดภาพหลักฐาน'),
        ),
    ]
