# Generated by Django 3.2.3 on 2023-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0032_alter_notebook_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='name',
            field=models.CharField(max_length=60, verbose_name='ชื่อโน๊ตบุ๊ก'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='serial2',
            field=models.CharField(max_length=60, null=True, verbose_name='หมายเลขประจำเครื่อง'),
        ),
    ]
