# Generated by Django 3.2.3 on 2023-05-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0033_auto_20230518_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cable',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Create Cable'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Create Office'},
        ),
        migrations.AddField(
            model_name='cable',
            name='serial',
            field=models.CharField(max_length=60, null=True, verbose_name='รหัสสินค้า'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='date',
            field=models.DateField(verbose_name='วันที่เบิก'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='detail',
            field=models.TextField(max_length=255, null=True, verbose_name='อุปกรณ์เสริม'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='item_name',
            field=models.CharField(max_length=60, null=True, verbose_name='ชื่อสินค้า'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='name',
            field=models.CharField(max_length=60, verbose_name='ชื่อสินค้า'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='serial',
            field=models.CharField(max_length=60, null=True, verbose_name='รหัสสินค้า'),
        ),
    ]
