# Generated by Django 3.2.3 on 2023-05-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0034_auto_20230523_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='item_name',
            new_name='name',
        ),
    ]
