# Generated by Django 3.2.3 on 2023-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0037_alter_stock_quatity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่'),
        ),
    ]
