# Generated by Django 3.2.3 on 2023-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0038_auto_20230530_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่'),
        ),
    ]
