# Generated by Django 3.2.3 on 2023-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyfinance',
            name='created_dat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moneyfinance',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moneyfinance',
            name='money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='moneyfinance',
            name='pgitve',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='moneyfinance',
            name='presive',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
