# Generated by Django 3.2.3 on 2023-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_money', '0003_sorary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyfinance',
            old_name='pgitve',
            new_name='pgife',
        ),
        migrations.RemoveField(
            model_name='sorary',
            name='username',
        ),
        migrations.AddField(
            model_name='sorary',
            name='outmoney',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyfinance',
            name='created_dat',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moneyfinance',
            name='money',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
