# Generated by Django 3.2.3 on 2023-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_money', '0004_auto_20230411_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyfinance',
            name='created_dat',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
