# Generated by Django 3.2.3 on 2023-04-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_money', '0005_alter_moneyfinance_created_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyfinance',
            old_name='name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='moneyfinance',
            name='pgife',
        ),
        migrations.RemoveField(
            model_name='moneyfinance',
            name='presive',
        ),
    ]
