# Generated by Django 3.2.3 on 2023-04-11 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_money', '0006_auto_20230411_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='image_money')),
                ('subject', models.CharField(max_length=255)),
                ('money', models.PositiveBigIntegerField(blank=True, default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_dat', models.DateField(auto_now_add=True, null=True)),
                ('collector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MoneyFinance',
        ),
    ]
