# Generated by Django 3.2.3 on 2023-03-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_team', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_customer', models.IntegerField(default=0)),
                ('slakthai', models.IntegerField(default=0)),
                ('mughuay', models.IntegerField(default=0)),
                ('member', models.IntegerField(default=0)),
                ('pay', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.profileuser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_team.team')),
            ],
        ),
    ]
