# Generated by Django 3.2.3 on 2023-03-28 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
