# Generated by Django 3.2.3 on 2023-03-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0003_alter_kpi_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
