# Generated by Django 3.2.3 on 2023-05-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0025_auto_20230501_1642'),
        ('app_kpi', '0004_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.team'),
        ),
    ]
