# Generated by Django 3.2.3 on 2023-05-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0045_auto_20230504_1010'),
        ('app_kpi', '0008_alter_dashboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.team'),
        ),
    ]
