# Generated by Django 3.2.3 on 2023-05-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0009_alter_dashboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user',
            new_name='team',
        ),
    ]
