# Generated by Django 3.2.3 on 2023-05-05 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_kpi', '0010_rename_user_dashboard_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thaiban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_customer', models.CharField(max_length=255, verbose_name='username ')),
                ('user_password', models.CharField(max_length=255, verbose_name='password ')),
                ('user_telephone', models.CharField(max_length=255, verbose_name='username ')),
                ('user_buy', models.BooleanField(default=False)),
                ('user_qutity', models.PositiveIntegerField()),
                ('page_name', models.CharField(max_length=255, verbose_name='ที่มาลูกค้า')),
                ('detail', models.CharField(max_length=255, verbose_name='รายละเอียดเพิ่มเติม')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
