# Generated by Django 3.2.3 on 2023-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0014_auto_20230505_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Interrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ประเภทลูกค้า')),
            ],
        ),
        migrations.RemoveField(
            model_name='thaiban',
            name='user_password',
        ),
    ]
