# Generated by Django 3.2.3 on 2023-05-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0015_auto_20230505_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='thaiban',
            name='unit',
            field=models.CharField(blank=True, choices=[('บาท', 'บาท'), ('ใบ', 'ใบ'), ('ครั้ง', 'ครั้ง')], max_length=10),
        ),
        migrations.AddField(
            model_name='thaiban',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_kpi.user_interrest'),
        ),
    ]
