# Generated by Django 3.2.3 on 2023-05-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0017_rename_thaiban_customer_interest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Interrest',
            new_name='Create_Interrest',
        ),
    ]
