# Generated by Django 3.2.3 on 2023-04-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='image_team'),
        ),
    ]
