# Generated by Django 3.2.3 on 2023-05-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0023_auto_20230501_0928'),
        ('app_team', '0002_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_at',
            new_name='created_dat',
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.profileuser'),
        ),
    ]
