# Generated by Django 3.2.3 on 2023-05-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0003_auto_20230501_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
    ]
