# Generated by Django 3.2.3 on 2023-05-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0023_auto_20230501_0928'),
        ('app_team', '0004_auto_20230501_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='choose_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_team.create_team'),
        ),
        migrations.AddField(
            model_name='team',
            name='suser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.profileuser'),
        ),
    ]
