# Generated by Django 3.2.3 on 2023-05-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0005_auto_20230501_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='suser',
            new_name='user',
        ),
    ]
