# Generated by Django 3.2.3 on 2023-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0006_rename_suser_team_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_dat',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='choose_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Create_Team',
        ),
    ]
