# Generated by Django 3.2.3 on 2023-05-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0005_alter_kpi_team'),
        ('app_team', '0007_auto_20230501_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
