# Generated by Django 3.2.3 on 2023-05-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0009_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['id'], 'verbose_name': 'Group & Team', 'verbose_name_plural': 'Membership'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'Group & Team', 'verbose_name_plural': 'Person'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
