# Generated by Django 3.2.3 on 2023-05-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_team', '0010_auto_20230502_1251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table='Member',
        ),
    ]
