# Generated by Django 3.2 on 2023-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20230330_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='position',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
