# Generated by Django 3.2 on 2023-04-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_alter_profileuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='id_user',
            field=models.IntegerField(blank=True, default=1001),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
