# Generated by Django 3.2 on 2023-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_auto_20230402_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
