# Generated by Django 3.2 on 2023-04-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_auto_20230402_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='salary',
        ),
    ]
