# Generated by Django 3.2 on 2023-04-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_profileuser_sorary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='sorary',
        ),
    ]
