# Generated by Django 3.2 on 2023-04-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_money', '0003_sorary'),
        ('app_user', '0009_remove_profileuser_sorary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='sora',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app_money.sorary'),
            preserve_default=False,
        ),
    ]
