# Generated by Django 3.2 on 2023-04-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_profileuser_sora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='sora',
        ),
    ]
