# Generated by Django 3.2 on 2023-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_remove_profileuser_sora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='usertype',
            new_name='team',
        ),
    ]
