# Generated by Django 3.2.3 on 2023-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_rename_usertype_profileuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='sorary',
            field=models.IntegerField(default=9000),
        ),
    ]
