# Generated by Django 3.2.3 on 2023-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_profileuser_sorary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='dayofwork',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='ot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='worklate',
            field=models.IntegerField(default=0),
        ),
    ]
