# Generated by Django 3.2.3 on 2023-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0014_auto_20230402_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='la',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='money_advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='money_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='money_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='money_traff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='sick',
            field=models.IntegerField(default=0),
        ),
    ]
