# Generated by Django 3.2.3 on 2023-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_alter_profileuser_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='create',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='dayofwork',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='la',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='money_advance',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='money_food',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='money_home',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='money_traff',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='ot',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='sick',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='sorary',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='team',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='worklate',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='num_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='position',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
