# Generated by Django 3.2.3 on 2023-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0017_auto_20230418_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='talen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
