# Generated by Django 3.2.3 on 2023-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0020_rename_details_profileuser_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='num_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='talen',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='worked',
            new_name='working_experience',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='lastname',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='id_user',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
