# Generated by Django 3.2.3 on 2023-05-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0021_auto_20230501_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
