# Generated by Django 3.2.3 on 2023-05-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0025_auto_20230501_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'ordering': ['id'], 'verbose_name': 'Name Position', 'verbose_name_plural': 'Create Position'},
        ),
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['id'], 'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id'], 'verbose_name': 'Name Skill', 'verbose_name_plural': 'Create Skill'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name': 'Name Team', 'verbose_name_plural': 'Create Team'},
        ),
    ]
