# Generated by Django 3.2.3 on 2023-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0026_auto_20230502_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['-id'], 'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
