# Generated by Django 3.2.3 on 2023-05-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0028_alter_profileuser_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
