# Generated by Django 3.2.3 on 2023-05-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0029_alter_profileuser_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='skill',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='working_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.skill'),
        ),
    ]
