# Generated by Django 3.2.3 on 2023-05-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0032_auto_20230502_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='create_date',
            new_name='date',
        ),
    ]
