# Generated by Django 3.2.3 on 2023-05-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0033_rename_create_date_profileuser_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='date',
        ),
    ]
