# Generated by Django 3.2.3 on 2023-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0034_remove_profileuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
