# Generated by Django 3.2.3 on 2023-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0035_profileuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='date',
            field=models.DateField(),
        ),
    ]
