# Generated by Django 3.2.3 on 2023-05-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0036_alter_profileuser_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='date',
            new_name='worked_date',
        ),
    ]
