# Generated by Django 3.2.3 on 2023-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0037_rename_date_profileuser_worked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='working_experience',
            field=models.CharField(blank=True, choices=[('1ปี', '1ปี'), ('2ปี', '2ปี'), ('มากกว่า3ปี', 'มากกว่า3ปี')], default='ไม่มีประสบการณ์', max_length=10),
        ),
    ]
