# Generated by Django 3.2.3 on 2023-05-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0038_alter_profileuser_working_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='working_experience',
            field=models.CharField(blank=True, choices=[('ไม่ระบุ', 'ไม่ระบุ'), ('ตำกว่า1', 'ตำกว่า1'), ('ปี1ปี', 'ปี1ปี'), ('2ปี', '2ปี'), ('มากกว่า3ปี', 'มากกว่า3ปี')], max_length=10),
        ),
    ]
