# Generated by Django 3.2.3 on 2023-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0039_alter_profileuser_working_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['-username'], 'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='working_experience',
            field=models.CharField(blank=True, choices=[('ต่ำกว่า1ปี', 'ต่ำกว่า1ปี'), ('1ปี', '1ปี'), ('2ปี', '2ปี'), ('มากกว่า3ปี', 'มากกว่า3ปี')], max_length=10),
        ),
    ]
