# Generated by Django 3.2.3 on 2023-05-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0040_auto_20230502_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='worked_date',
        ),
    ]
