# Generated by Django 3.2.3 on 2023-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0041_remove_profileuser_worked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
