# Generated by Django 3.2.3 on 2023-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0042_alter_profileuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
