# Generated by Django 3.2.3 on 2023-05-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0043_auto_20230502_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['-username'], 'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AddField(
            model_name='profileuser',
            name='worked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
