# Generated by Django 3.2.3 on 2023-05-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0044_auto_20230502_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'ordering': ['-id'], 'verbose_name': 'Name Position', 'verbose_name_plural': 'Create Position'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id'], 'verbose_name': 'Name Skill', 'verbose_name_plural': 'Create Skill'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id'], 'verbose_name': 'Name Team', 'verbose_name_plural': 'Create Team'},
        ),
    ]
