# Generated by Django 3.2.3 on 2023-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0045_auto_20230504_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='image_teams', verbose_name='สัญญาลักษณ์ทีม'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ตำแหน่งงาน'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='สกิลการทำงาน'),
        ),
        migrations.AlterField(
            model_name='team',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อทีม'),
        ),
    ]
