# Generated by Django 3.2.3 on 2023-05-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0047_alter_profileuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='image_check',
            field=models.BooleanField(default=False),
        ),
    ]
