# Generated by Django 3.2.3 on 2023-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0048_profileuser_image_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
