# Generated by Django 3.2.3 on 2023-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0049_positions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='ชื่อพนักงาน'),
        ),
    ]
