# Generated by Django 3.2.3 on 2023-05-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0051_auto_20230529_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='slug',
        ),
    ]
