# Generated by Django 3.2.3 on 2023-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0052_remove_positions_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='other',
            field=models.TextField(blank=True, max_length=255, verbose_name='หมายเหตุ'),
        ),
    ]
