# Generated by Django 3.2.3 on 2023-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0053_profileuser_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='working_experience',
            field=models.CharField(blank=True, choices=[('น้อยกว่า1ปี', 'น้อยกว่า1ปี'), ('1ปี', '1ปี'), ('2ปี', '2ปี'), ('มากกว่า3ปี', 'มากกว่า3ปี')], max_length=20, verbose_name='ประสบการณ์ทำงาน'),
        ),
    ]
