# Generated by Django 3.2.3 on 2023-06-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0054_alter_profileuser_working_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='permission',
            field=models.CharField(blank=True, choices=[('Lv1', 'Lv1'), ('Lv2', 'Lv2'), ('Lv3', 'Lv3'), ('Lv4', 'Lv4'), ('Lv5', 'Lv5')], max_length=3, verbose_name='สิทธิ์การใช้งาน'),
        ),
    ]
