# Generated by Django 3.2.3 on 2023-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0055_profileuser_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='permission',
            field=models.CharField(blank=True, choices=[('ฝ่ายการตลาด', 'ฝ่ายการตลาด'), ('ฝ่ายสต๊อกสินค้า', 'ฝ่ายสต๊อกสินค้า'), ('ฝ่ายการเงินการบัญชี', 'ฝ่ายการเงินการบัญชี'), ('ฝ่ายบุคคล', 'ฝ่ายบุคคล')], max_length=21, verbose_name='สิทธิ์การใช้งาน'),
        ),
    ]
